Hi, my name is Bunmi and I'll be taking you lessons on Fundamentals of Data Science. In this notebook, I'll be using python.

This Tutorial Session is going to cover the following points

  1. What Is Data All About?


  2. How Statistics Is Related To Data Science ?


  3. Why Is Statistics Important For Data Science ?


  4. How is data gathered, stored and processed ?
  
  
  5. Introduction to Pandas and Numpy
  
  
  6. Statistical Analysis of Data using Numpy and Pandas


  5. Exercises
  
I am going to take this class assumming that you already know python and can write a few lines of python codes


So, lets start with the definitions ;

1. What is Data All About ?

      Data Science according to Wikipedia is defined as a multi-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from structured and unstructured data.
         
      Data Science is alsothe extraction of knowledge from data, using ideas from mathematics, statistics, machine learning, computer programming, data engineering, etc
      
      I define Data Science asthe process by which raw data undergoes cleaning, analysis, restructuring and other manipulations which requires understanding of the data given to be able to make correct predictions on the data.

2. What is Statistics ?

      Statistics is mainly the study of the collection, analysis, interpretation, presentation, and organization of data.
      
3. How Is Statistics Related To Data Science ?

      Data science combines multidisciplinary fields to interpret data for decision making whereas statistics refers to mathematical analysis which use quantified models to represent a given set of data.
      
      Statistics provides the methodology to collect , analyse and make conclusions from data. It is very useful for data analysis.
      
4. Why then is Statistics important to Data Science ?
 
      Statistics allows us to represent variability in the data as well as a prior knowledge of parameters, the concept underlying Bayesian statistics .
      
      Statistical distributions also enable us to choose adequate subsequent analytic models and methods.
   
5. How Is Data Gathered And Stored ?
    
    
    
      
Now that I have answered these questions, time for the main business !

In python, there are a lots of libaries used for statistics , I'll name a few

1. Numpy

2. Pandas

3. Matplotlib

4. Scipy

5. Scikit-Learn

6. TensorFlow

7. Keras, and so on

I'll talk about the first four.

1. Numpy :

    NumPy, short for Numerical Python, is the foundational package for scientific computing in Python is a fundamental Python libary meant for scientific computing. It comes with a powerful N-dimensional array object and broadcating functions. 
    
    One of its primary purposes with regards to data analysis is as the primary container for data to be passed between algorithms. What do I mean ?
    
    For numerical data, NumPy arrays are a much more efficient way of storing and manipulating data than the other built-in Python data structures. 
    
2. Pandas

    Pandas provides rich data structures and functions designed to make working with structured data fast, easy, and expressive.
    
    It is, as you will see, one of the critical ingredients enabling Python to be a powerful and productive data analysis environment. 
    
    It aims to serve as the fudamental high-level building block for carrying out real-world data analysis using python. 
    
    One of its most powerful features is to translate complex data Operations using mere one or two commands, it also features time sereies functionality.
    
3. Matplotlib :
    Matplotlib is a two-dimensional plotting libary for  Python . It is capable of producing high-quality figures in different hardcopy formats and interactive cross-platform. It is usually used in Python shell, Python scripts, Ipython shell, Jupyter Notebook, GUI toolkits.
    
4. Scipy :
    SciPy is a collection of packages addressing a number of different standard problem domains in scientific computing. It comes with alot of modules for integration, linear algebra, optimization and statistics. Numppy arrays are basic structures used by SciPy.  Here is a sampling of the packages included:
    
    • scipy.integrate: numerical integration routines and differential equation solvers 
    
    • scipy.linalg: linear algebra routines and matrix decompositions extending beyond those provided in numpy.linalg.
    
    • scipy.optimize: function optimizers (minimizers) and root finding algorithms
    
    • scipy.signal: signal processing tools 
    
    • scipy.sparse: sparse matrices and sparse linear system solvers
    
    • scipy.stats: standard continuous and discrete probability distributions (density functions, samplers, continuous distribution functions), various statistical tests, and more descriptive statistics
    
    
      But, for the purpose of this class, I'll limit us to just Numpy and Pandas
      
      I'll recommend that you have Anaconda installed on your system and working.
      
So, lets start with Numpy !

In [1]:
# importing Numpy
import numpy as np
print(np.__version__)

1.16.4


Lets begin with a few simple operations.

In [2]:
# Lets create a numpy array first
# Creating an array from a list of numbers
np_array = np.array([1, 2, 3, 4, 5, 6])
np_array

array([1, 2, 3, 4, 5, 6])

In [3]:
# Creating an array from two lists of numbers
np_array_2 = np.array([[1, 2, 3], [4, 5, 6]])
np_array_2
# This is also known as a 2-dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Creating an array from three list of numbers
np_array_3 = np.array([[1, 2, 3], [2, 3, 4], [4, 5, 6]])
np_array_3
# This is also known as a three dimensional data

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [5]:
# Lets calculatethe mean 
print('The mean of 1-d array is :',np.mean(np_array))
print('The mean of 2-d array is :',np.mean(np_array_2))
print('The mean of 3-d array is :',np.mean(np_array_3))

The mean of 1-d array is : 3.5
The mean of 2-d array is : 3.5
The mean of 3-d array is : 3.3333333333333335


In [6]:
# the median
print('The median of 1-d array is :',np.median(np_array))
print('The median of 2-d array is :',np.median(np_array_2))
print('The median of 3-d array is :',np.median(np_array_3))

The median of 1-d array is : 3.5
The median of 2-d array is : 3.5
The median of 3-d array is : 3.0


In [7]:
# You cant calculate the mode ofan array using np.mode, we will treat this later in pandas
# the standard deviation
print('The standard deviation of 1-d array is :',np.std(np_array))
print('The standard deviation of 2-d array is :',np.std(np_array_2))
print('The standard deviation of 3-d array is :',np.std(np_array_3))

The standard deviation of 1-d array is : 1.707825127659933
The standard deviation of 2-d array is : 1.707825127659933
The standard deviation of 3-d array is : 1.4907119849998598


In [8]:
# You can also create a numpy array using a built in function known as np.arange
# arange is an array-valued version of the built-in Python range function:
# i.e , it returns an array instead of a list
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
# To check the shape of an array
np.arange(15).shape

(15,)

In [11]:
# Here, we created an array and decide to reshape it from (15, 1) to a (5, 3) array
np.arange(15.).reshape((3, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [12]:
np.arange(15.).reshape((3, 5)).shape

(3, 5)

In [13]:
# you can also find the datatype of an array by using the .dtype function
np.arange(15.).dtype

dtype('float64')

In [14]:
# you can also convert an array from one datatype to the other using .astype function
np.arange(15.).astype(np.int64)# 64 bit integer

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

<h3>
    
   Here is a simple classwork :
    
   1. Create a multidimensional array for a range of 50 numbers
    
    
   2. using the same array, give various transformations the array can undergo
    
    
   3. Find the mean, median and standard deviation of the array
   
   
   4. Create a dataframe for five of your friends in a range of 50

In [15]:
s3 = np.arange(20).reshape((4, 5))
s3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
# We can also perform various selections such as selecting the second row in the array
s3[1]

array([5, 6, 7, 8, 9])

In [17]:
s3[1:5]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
# subtracting the first row from the original array
s3 - s3[1]

array([[-5, -5, -5, -5, -5],
       [ 0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10]])

In [19]:
s3[1]-10

array([-5, -4, -3, -2, -1])

In [20]:
s3[0][2]
# gives the value in the first row, third column

2

In [21]:
s3[1][4]

9

In [22]:
# Square root of an array
np.sqrt(s3)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [23]:
# the exponential of an array
np.exp(s3)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08]])

In [24]:
-s3

array([[  0,  -1,  -2,  -3,  -4],
       [ -5,  -6,  -7,  -8,  -9],
       [-10, -11, -12, -13, -14],
       [-15, -16, -17, -18, -19]])

In [25]:
# to convert a negative array to a +ve one use .abs
np.abs(-s3)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
# we can arrange the values in an array in descending order
s3.sort()
s3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Now, moving on to Pandas

In pandas, we can either have a Series a Dataframe, or a Panel

What is a Series ?
A Series is a one-dimensional array-like object containing an array of data (of any NumPy data type) and an associated array of data labels, called its index. The simplest Series is formed from only an array of data. Series is a 1D labeled homogeneously-typed array

What is a DataFrame ?
A DataFrame represents a tabular, spreadsheet-like data structure containing an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dict of Series (one for all sharing the same index). DataFrame is a general 2D labeled, size-mutable tabular structure with potentially heterogeneously-typed columns

What is a Panel ?

 The term panel data is derived from econometrics and is partially responsible for the name pandas: pan(el)-da(ta)-s. The names for the 3 axes are intended to give some semantic meaning to describing operations involving panel data and, in particular, econometric analysis of panel data. However, for the strict purposes of slicing and dicing a collection of DataFrame objects, you may find the axis names slightly arbitrary: 
 
 • items: axis 0, each item corresponds to a DataFrame contained inside
 • major_axis: axis 1, it is the index(rows) of each of the DataFrames 
 • minor_axis: axis 2, it is the columns of each of the DataFrames 
 
Panel General 3D labeled, also size-mutable array

Lets start with Series

In [27]:
# importing pandas
import pandas as pd
ser = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
ser

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [28]:
ser.values

array([1, 2, 3, 4, 5], dtype=int64)

In [29]:
ser.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [30]:
ser[2]*4

12

In [31]:
s2 = pd.Series(np.arange(5))

In [32]:
ser + s2
# This is because they dont have the same index

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [33]:
s3 = pd.Series(np.arange(7), index=list('abcdefg'))
s3

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int32

In [34]:
ser + s3

a    1.0
b    3.0
c    5.0
d    7.0
e    9.0
f    NaN
g    NaN
dtype: float64

In [35]:
ser - s3

a    1.0
b    1.0
c    1.0
d    1.0
e    1.0
f    NaN
g    NaN
dtype: float64

In [36]:
ser * s3

a     0.0
b     2.0
c     6.0
d    12.0
e    20.0
f     NaN
g     NaN
dtype: float64

In [37]:
ser / s3
# 0 / 0 is infinite

a         inf
b    2.000000
c    1.500000
d    1.333333
e    1.250000
f         NaN
g         NaN
dtype: float64

Moving on to dataframes

In [38]:
#We can create a dataframe from a dictionary
dict1 = {'one' : pd.Series([1., 2., 3., 7], index=['a', 'b', 'c', 'd']), 'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])} 

In [39]:
df = pd.DataFrame(dict1)
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  7.0  4.0

In [40]:
pd.DataFrame(dict1, index=['d', 'b', 'a']) 

one  two
d  7.0  4.0
b  2.0  2.0
a  1.0  1.0

In [41]:
# from ndarrays or lists
# The ndarrays must all be the same length. If an index is passed, it must clearly also be the same length as the arrays. 
# If no index is passed, the result will be range(n), where n is the array length.
dict2 = {'first':np.arange(10), 'secnd':np.arange(10, 20)}

In [42]:
pd.DataFrame(dict2)

first  secnd
0      0     10
1      1     11
2      2     12
3      3     13
4      4     14
5      5     15
6      6     16
7      7     17
8      8     18
9      9     19

<h3 > Lets move to Selection and Slicing methods </h3>

<b> There are various methods for selection and slicing which include:
    
   1. .iloc method, which is positional oriented
   
   
   2. .loc method, which is label oriented
   
   
   3. the general method , .ix which can behave as the .iloc or .loc fuction, depending on the type of arguments passed into it

In [43]:
# create a dataframe and a copy
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 2, 2, 1, 2],
                   'B': [1, 2, 3, 4, 2, 4],
                   'C': [3, 4, 6, 6, 5, 1],
                   }, index=['a', 'b', 'c', 'd', 'e', 'f'])
df2 = df.copy()

In [44]:
df

A  B  C
a  1  1  3
b  2  2  4
c  2  3  6
d  2  4  6
e  1  2  5
f  2  4  1

In [45]:
print(df.iloc[0])

print(df.loc['a'])

#print(df.iloc['a'])
# prints out all the values on row a i.e position
# df.iloc['a'] gives an error because the position of a is 0 since it is the first row. i.e position oriented

A    1
B    1
C    3
Name: a, dtype: int64
A    1
B    1
C    3
Name: a, dtype: int64


In [46]:
df.iloc[1:4]

A  B  C
b  2  2  4
c  2  3  6
d  2  4  6

In [47]:
df.loc['c':'e']# it is label oriented
# prints out the rows with labels from 1 to 3

A  B  C
c  2  3  6
d  2  4  6
e  1  2  5

In [48]:
df.ix[0:3] # same as .iloc[0:3], it is general

C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A  B  C
a  1  1  3
b  2  2  4
c  2  3  6

In [49]:
df.ix['a': 'd'] # same as .loc['a':'d']

C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A  B  C
a  1  1  3
b  2  2  4
c  2  3  6
d  2  4  6

In [50]:
# creating a dataframe using random numbers which contain negative numbers
d4 = pd.DataFrame(np.random.randn(4, 3), columns=list('abc'), index=np.arange(4))
d4

a         b         c
0 -2.030643  0.550329 -0.344068
1  0.381677  0.071595 -0.722977
2  0.314379  0.407667  0.310344
3  1.568394 -2.384506 -0.490804

In [51]:
# To convert all the negative values in a dataframe to positive, use the absolute function .abs()
np.abs(d4)

a         b         c
0  2.030643  0.550329  0.344068
1  0.381677  0.071595  0.722977
2  0.314379  0.407667  0.310344
3  1.568394  2.384506  0.490804

In [52]:
# You can also take the sum of all the rows by the columns
d4.sum()

a    0.233808
b   -1.354915
c   -1.247505
dtype: float64

In [53]:
d4.sum(axis=1)
# to sum the columns by the rows

0   -1.824382
1   -0.269705
2    1.032391
3   -1.306916
dtype: float64

In [54]:
# instead of performing individual statistics, pandas has a .describe() function that give the summary statistics of a dataframe
d4.describe()

a         b         c
count  4.000000  4.000000  4.000000
mean   0.058452 -0.338729 -0.311876
std    1.507118  1.378538  0.443175
min   -2.030643 -2.384506 -0.722977
25%   -0.271876 -0.542430 -0.548847
50%    0.348028  0.239631 -0.417436
75%    0.678356  0.443333 -0.180465
max    1.568394  0.550329  0.310344

<h3> Time for classwork . This time, I want you to :</h3>  
    

1. Create a dataset having the information of 7 diffrent school students on their names, matric number, and three courses they offer.

    
2. Give the summary statistics of each student and give the three best students in the dataset in order of their marks scored for each course

3. Give the total score for each course of the student

In [55]:

d5 = pd.Series(['q', 'q', 'w', 'q', 'r', 't'], index=np.arange(6))
d5

0    q
1    q
2    w
3    q
4    r
5    t
dtype: object

In [56]:
# for non numeric data, it also gives a summary statistics
d5.describe()

count     6
unique    4
top       q
freq      3
dtype: object

In [57]:
d6 = pd.DataFrame(np.arange(1000, 1500).reshape(25, -1), columns=list('abcdefghijklmnopqrst'), index=np.arange(25))
d6

# I just created a dataframe of numbers between 1000 and 1500 with columns between a and t and rows between 1 and 25

a     b     c     d     e     f     g     h     i     j     k     l  \
0   1000  1001  1002  1003  1004  1005  1006  1007  1008  1009  1010  1011   
1   1020  1021  1022  1023  1024  1025  1026  1027  1028  1029  1030  1031   
2   1040  1041  1042  1043  1044  1045  1046  1047  1048  1049  1050  1051   
3   1060  1061  1062  1063  1064  1065  1066  1067  1068  1069  1070  1071   
4   1080  1081  1082  1083  1084  1085  1086  1087  1088  1089  1090  1091   
5   1100  1101  1102  1103  1104  1105  1106  1107  1108  1109  1110  1111   
6   1120  1121  1122  1123  1124  1125  1126  1127  1128  1129  1130  1131   
7   1140  1141  1142  1143  1144  1145  1146  1147  1148  1149  1150  1151   
8   1160  1161  1162  1163  1164  1165  1166  1167  1168  1169  1170  1171   
9   1180  1181  1182  1183  1184  1185  1186  1187  1188  1189  1190  1191   
10  1200  1201  1202  1203  1204  1205  1206  1207  1208  1209  1210  1211   
11  1220  1221  1222  1223  1224  1225  1226  1227  1228  1229  1230  1231   
12  1240  1241  1242  1243  1244  1245  1246  1247  1248  1249  1250  1251   
13  1260  1261  1262  1263  1264  1265  1266  1267  1268  1269  1270  1271   
14  1280  1281  1282  1283  1284  1285  1286  1287  1288  1289  1290  1291   
15  1300  1301  1302  1303  1304  1305  1306  1307  1308  1309  1310  1311   
16  1320  1321  1322  1323  1324  1325  1326  1327  1328  1329  1330  1331   
17  1340  1341  1342  1343  1344  1345  1346  1347  1348  1349  1350  1351   
18  1360  1361  1362  1363  1364  1365  1366  1367  1368  1369  1370  1371   
19  1380  1381  1382  1383  1384  1385  1386  1387  1388  1389  1390  1391   
20  1400  1401  1402  1403  1404  1405  1406  1407  1408  1409  1410  1411   
21  1420  1421  1422  1423  1424  1425  1426  1427  1428  1429  1430  1431   
22  1440  1441  1442  1443  1444  1445  1446  1447  1448  1449  1450  1451   
23  1460  1461  1462  1463  1464  1465  1466  1467  1468  1469  1470  1471   
24  1480  1481  1482  1483  1484  1485  1486  1487  1488  1489  1490  1491   

       m     n     o     p     q     r     s     t  
0   1012  1013  1014  1015  1016  1017  1018  1019  
1   1032  1033  1034  1035  1036  1037  1038  1039  
2   1052  1053  1054  1055  1056  1057  1058  1059  
3   1072  1073  1074  1075  1076  1077  1078  1079  
4   1092  1093  1094  1095  1096  1097  1098  1099  
5   1112  1113  1114  1115  1116  1117  1118  1119  
6   1132  1133  1134  1135  1136  1137  1138  1139  
7   1152  1153  1154  1155  1156  1157  1158  1159  
8   1172  1173  1174  1175  1176  1177  1178  1179  
9   1192  1193  1194  1195  1196  1197  1198  1199  
10  1212  1213  1214  1215  1216  1217  1218  1219  
11  1232  1233  1234  1235  1236  1237  1238  1239  
12  1252  1253  1254  1255  1256  1257  1258  1259  
13  1272  1273  1274  1275  1276  1277  1278  1279  
14  1292  1293  1294  1295  1296  1297  1298  1299  
15  1312  1313  1314  1315  1316  1317  1318  1319  
16  1332  1333  1334  1335  1336  1337  1338  1339  
17  1352  1353  1354  1355  1356  1357  1358  1359  
18  1372  1373  1374  1375  1376  1377  1378  1379  
19  1392  1393  1394  1395  1396  1397  1398  1399  
20  1412  1413  1414  1415  1416  1417  1418  1419  
21  1432  1433  1434  1435  1436  1437  1438  1439  
22  1452  1453  1454  1455  1456  1457  1458  1459  
23  1472  1473  1474  1475  1476  1477  1478  1479  
24  1492  1493  1494  1495  1496  1497  1498  1499

In [58]:
# This is how I got the size of the rows and columns
a = np.arange(1000, 1500).reshape(25, -1)

In [59]:
a.shape

(25, 20)

Lets continue

In [60]:
# to calculate the percentage of each variable
a = d6.pct_change()
# To show the last 5 rows of the datframe
a.tail()

a         b         c         d         e         f         g  \
20  0.014493  0.014482  0.014472  0.014461  0.014451  0.014440  0.014430   
21  0.014286  0.014276  0.014265  0.014255  0.014245  0.014235  0.014225   
22  0.014085  0.014075  0.014065  0.014055  0.014045  0.014035  0.014025   
23  0.013889  0.013879  0.013870  0.013860  0.013850  0.013841  0.013831   
24  0.013699  0.013689  0.013680  0.013671  0.013661  0.013652  0.013643   

           h         i         j         k         l         m         n  \
20  0.014420  0.014409  0.014399  0.014388  0.014378  0.014368  0.014358   
21  0.014215  0.014205  0.014194  0.014184  0.014174  0.014164  0.014154   
22  0.014015  0.014006  0.013996  0.013986  0.013976  0.013966  0.013957   
23  0.013822  0.013812  0.013803  0.013793  0.013784  0.013774  0.013765   
24  0.013633  0.013624  0.013615  0.013605  0.013596  0.013587  0.013578   

           o         p         q         r         s         t  
20  0.014347  0.014337  0.014327  0.014316  0.014306  0.014296  
21  0.014144  0.014134  0.014124  0.014114  0.014104  0.014094  
22  0.013947  0.013937  0.013928  0.013918  0.013908  0.013899  
23  0.013755  0.013746  0.013736  0.013727  0.013717  0.013708  
24  0.013569  0.013559  0.013550  0.013541  0.013532  0.013523

In [61]:
# To find the correlation between all the columns with respect to each other
a.corr()

a         b         c         d         e         f         g    h  \
a  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
b  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
c  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
d  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
e  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
f  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
g  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
h  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
i  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
j  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
k  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
l  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
m  0.999999  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
n  0.999999  0.999999  1.000000  1.000000  1.000000  1.000000  1.000000  1.0   
o  0.999999  0.999999  0.999999  1.000000  1.000000  1.000000  1.000000  1.0   
p  0.999999  0.999999  0.999999  0.999999  1.000000  1.000000  1.000000  1.0   
q  0.999999  0.999999  0.999999  0.999999  0.999999  1.000000  1.000000  1.0   
r  0.999999  0.999999  0.999999  0.999999  0.999999  1.000000  1.000000  1.0   
s  0.999999  0.999999  0.999999  0.999999  0.999999  0.999999  1.000000  1.0   
t  0.999999  0.999999  0.999999  0.999999  0.999999  0.999999  0.999999  1.0   

     i    j    k    l         m         n         o         p         q  \
a  1.0  1.0  1.0  1.0  0.999999  0.999999  0.999999  0.999999  0.999999   
b  1.0  1.0  1.0  1.0  1.000000  0.999999  0.999999  0.999999  0.999999   
c  1.0  1.0  1.0  1.0  1.000000  1.000000  0.999999  0.999999  0.999999   
d  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  0.999999  0.999999   
e  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  0.999999   
f  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
g  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
h  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
i  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
j  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
k  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
l  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
m  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
n  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
o  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
p  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
q  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
r  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
s  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   
t  1.0  1.0  1.0  1.0  1.000000  1.000000  1.000000  1.000000  1.000000   

          r         s         t  
a  0.999999  0.999999  0.999999  
b  0.999999  0.999999  0.999999  
c  0.999999  0.999999  0.999999  
d  0.999999  0.999999  0.999999  
e  0.999999  0.999999  0.999999  
f  1.000000  0.999999  0.999999  
g  1.000000  1.000000  0.999999  
h  1.000000  1.000000  1.000000  
i  1.000000  1.000000  1.000000  
j  1.000000  1.000000  1.000000  
k  1.000000  1.000000  1.000000  
l  1.000000  1.000000  1.000000  
m  1.000000  1.000000  1.000000  
n  1.000000  1.000000  1.000000  
o  1.000000  1.000000  1.000000  
p  1.000000  1.000000  1.000000  
q  1.000000  1.000000  1.000000  
r  1.000000  1.000000  1.000000  
s  1.000000  1.000000  1.000000  
t  1.000000  1.000000  1.000000

In [62]:
#To find the correlation between two columns : column 1 and column 18,
a.a.corr(a.r)

0.9999989885618293

In [63]:
# To find the correlation of a column 'o' and the rest of the columns,
a.corrwith(a.o)

a    0.999999
b    0.999999
c    0.999999
d    1.000000
e    1.000000
f    1.000000
g    1.000000
h    1.000000
i    1.000000
j    1.000000
k    1.000000
l    1.000000
m    1.000000
n    1.000000
o    1.000000
p    1.000000
q    1.000000
r    1.000000
s    1.000000
t    1.000000
dtype: float64

In [64]:
# you can even find the correlation between two different dataframes
a.corrwith(d4)

a   -0.835013
b    0.798879
c   -0.225149
d         NaN
e         NaN
f         NaN
g         NaN
h         NaN
i         NaN
j         NaN
k         NaN
l         NaN
m         NaN
n         NaN
o         NaN
p         NaN
q         NaN
r         NaN
s         NaN
t         NaN
dtype: float64

Lets talk a little about Panels

In [65]:
frame2 = pd.DataFrame({'A': [1000, 1200, 1300, 1250, 1400, 1000, 1200, 1300, 1250, 1400, 5000, 3000],
                       'B': [200, 210, 220, 230, 250, 270, 240, 270, 200, 3000, 700, 1000],
                       'C': [1, 2, 3, 2, 1, 4, 4, 5, 100, 60, 7, 7]},
                      index=np.arange(12))
frame3 = pd.DataFrame(np.arange(36).reshape(12, 3), columns=list('DEF'))
frame4 = pd.DataFrame(np.random.randn(12, 3), columns=list('GHI'))

In [66]:
panel_1 = pd.Panel({'frame1':frame2, 'frame2':frame3, 'frame3':frame4})
panel_1

C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\IPython\core\interactiveshell.py:3325: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\pandas\core\panel.py:155: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  minor_axis=minor_axis, copy=copy, dtype=dtype)


<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 12 (major_axis) x 9 (minor_axis)
Items axis: frame1 to frame3
Major_axis axis: 0 to 11
Minor_axis axis: A to I

Idioms in Pandas

In [67]:
# I am assuming you guys are familiar with python dictionaries well
# Lets create a dataframe to work with
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]})
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [68]:
# an if-then statement on a column
df.ix[df.AAA >= 5, 'BBB'] = -1
df

C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


AAA  BBB  CCC
0    4   10  100
1    5   -1   50
2    6   -1  -30
3    7   -1  -50

In [69]:
# an if-then to two columns
df.ix[df.AAA >= 5, ['BBB', 'CCC']] = 555
df

C:\Users\Bunmi\Anaconda3-2019\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


AAA  BBB  CCC
0    4   10  100
1    5  555  555
2    6  555  555
3    7  555  555

In [70]:
# or you can use a pandas mask
df_mask = pd.DataFrame({'AAA' : [True]*4, 'BBB':[False]*4, 'CCC':[True, False]*2})
df.where(df_mask, -200)

AAA  BBB  CCC
0    4 -200  100
1    5 -200 -200
2    6 -200  555
3    7 -200 -200

In [71]:
df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]})
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [72]:
# or you can create a new column based on a particular column in the dataframe
df['new']=np.where(df['BBB']> 20, 'high', 'low')
df
# same as an if-else statement only that we use numpy function np.where()

AAA  BBB  CCC   new
0    4   10  100   low
1    5   20   50   low
2    6   30  -30  high
3    7   40  -50  high

In [73]:
df.loc[(df['BBB'] > 25) | (df['CCC'] >= 75), 'AAA'] = 0.1

In [80]:
 #rank isalsoaDataFramemethodandcanrankeithertherows(axis=0)orthecolumns(axis=1). NaN valuesare excluded from the ranking.

 
 s = pd.Series(np.random.np.random.randn(5), index=list('abcde'))

In [81]:
s['d'] = s['b'] # so there's a tie

In [82]:
s.rank() 

a    4.0
b    2.5
c    1.0
d    2.5
e    5.0
dtype: float64

Assignments


1. Using the students dataset above, 

    a. . Give the students with the 2nd to 6th position in class

    b. If a new student is added to the class, what will be the total mark for that student in each course if the mean of each course increases by 5%

    c. Give the rank of each student from the highest to the lowest

    d. Write a python function that gives the top three students in the class for any class given

2. Create a dataframe of 10 columns having 100 rows

    a. create a subset of the dataframe (also a dataframe) with values from the 35th to 78th position

    b. for each item in the subset that is grater than 60, repalce with 0

    c. what is the maximum correlation each column can have with the other (apart from itself)


Thank you for participating!

If you have any questions, see me after the class

Good day!